config/routes.rb
Rails.application.routes.draw do

  resources :settings

  resources :valuation_items

  resources :purchase_order_items

  resources :payment_orders

  resources :valuations do |payment_order|
    resources :payment_orders
  end

  resources :purchase_orders do |purchase_order|
    resources :valuations 
  end  

  get 'purchase_orders/:id/change_orders' => 'purchase_orders#index'
  get 'change_orders' => 'purchase_orders#index'
  get 'purchase_orders/:id/clone' => 'purchase_orders#clone'

  resources :roles

  resources :suppliers

  resources :agents

  resources :customers

  resources :works

  resources :users

  resources :messages

  resources :conversations  

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  get 'welcome/index'

  root 'welcome#index'

end

app/models/agent.rb
class Agent < ActiveRecord::Base
	has_many :work_assignments, dependent: :destroy
	has_many :works, :through => :work_assignments
	belongs_to :customer

	attr_accessor :password
	validates :name, :email, :address, presence: true
	validates :works, presence: true	
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	belongs_to :work
	has_many :agents
	has_many :valuations

	validates :name, presence: true
	validates :address, presence: true
end

app/models/payment_order.rb
class PaymentOrder < ActiveRecord::Base
	has_many :purchase_order_items
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
	belongs_to :customer
	belongs_to :work
	belongs_to :supplier
	has_many :purchase_order_items, :dependent => :destroy, :autosave => true
	has_many :valuations
	has_many :childs, :class_name => "PurchaseOrder", :foreign_key => :parent_id
	belongs_to :parent, :class_name => "PurchaseOrder"
	#has_paper_trail
	accepts_nested_attributes_for :purchase_order_items, allow_destroy: true

	def total_value
		purchase_order_items.sum('quantity * price')
	end	

end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	belongs_to :work

	validates :name, :agent, :rif, :address, presence: true
	validates :work, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :assignments, dependent: :destroy
  has_many :roles, :through => :assignments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	acts_as_messageable

	#Returning any kind of identification you want for the model
	def name
	  return self.email
	end

	#Returning the email address of the model if an email should be sent for this object (Message or Notification).
	#If no mail has to be sent, return nil.
	def mailboxer_email(object)
	  #Check if an email should be sent for that object
	  #if true
	  return "define_email@on_your.model"
	  #if false
	  #return nil
	end

end

app/models/valuation.rb
class Valuation < ActiveRecord::Base
	belongs_to :purchase_order
	has_many :valuation_items, :dependent => :destroy, :autosave => true
	accepts_nested_attributes_for :purchase_order
	accepts_nested_attributes_for :valuation_items, allow_destroy: true
end

app/models/valuation_item.rb
class ValuationItem < ActiveRecord::Base
	attr_accessor :total
	belongs_to :valuation
	belongs_to :purchase_order_item
end

app/models/work.rb
class Work < ActiveRecord::Base
	has_many :suppliers
	belongs_to :customer

	validates :customer, presence: true
	validates :name, :address, presence: true	
end

app/models/work_assignment.rb
class WorkAssignment < ActiveRecord::Base
  belongs_to :agent
  belongs_to :work
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/toolbar/_messages.html.erb
<ul class="nav nav-pills" style="padding-bottom:20px;">
  <li role="presentation" <%= 'class=active' if controller.action_name == 'new' %>>
    <%= link_to new_message_path do %>
      <span class='glyphicon glyphicon-pencil'> <%= t('messages.new') %></span>
    <% end %>
  </li>
  <li role="presentation" <%= 'class=active' if params[:box] == 'inbox' %>>
    <%= link_to conversations_path(box: :inbox) do %>
      <span class='glyphicon glyphicon-inbox'>
      <%= t('messages.inbox') %>
      </span> (<%#= current_user.unread_messages_count %>)
    <% end %>  
  </li>
  <li role="presentation" <%= 'class=active' if params[:box] == 'sentbox' %>>
    <%= link_to conversations_path(box: :sentbox) do %>
      <span class='glyphicon glyphicon-inbox'>
      <%= t('messages.sent') %>
      </span>
    <% end %> 
  </li> 
  <li role="presentation" <%= 'class=active' if params[:box] == 'trash' %>>
    <%= link_to conversations_path(box: :trash) do %>
      <span class='glyphicon glyphicon-trash'>
      <%= t('messages.trash') %>
      </span>
    <% end %>
  </li>    
</ul>