config/routes.rb
Rails.application.routes.draw do

  resources :settings

  resources :valuation_items

  resources :purchase_order_items

  resources :payment_orders

  resources :valuations do |payment_order|
    resources :payment_orders
  end

  resources :purchase_orders do |purchase_order|
    resources :valuations 
  end  

  get 'purchase_orders/:id/change_orders' => 'purchase_orders#index'
  get 'change_orders' => 'purchase_orders#index'
  get 'purchase_orders/:id/clone' => 'purchase_orders#clone'

  resources :roles

  resources :suppliers

  resources :agents

  resources :customers

  resources :works

  resources :users

  resources :messages

  resources :conversations  

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  get 'welcome/index'

  root 'welcome#index'

end

app/models/agent.rb
class Agent < ActiveRecord::Base
	has_many :work_assignments, dependent: :destroy
	has_many :works, :through => :work_assignments
	belongs_to :customer

	attr_accessor :password
	validates :name, :email, :address, presence: true
	validates :works, presence: true	
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	belongs_to :work
	has_many :agents
	has_many :valuations

	validates :name, presence: true
	validates :address, presence: true
end

app/models/payment_order.rb
class PaymentOrder < ActiveRecord::Base
	has_many :purchase_order_items
end

app/models/purchase_order.rb
class PurchaseOrder < ActiveRecord::Base
	belongs_to :customer
	belongs_to :work
	belongs_to :supplier
	has_many :purchase_order_items, :dependent => :destroy, :autosave => true
	has_many :valuations
	has_many :childs, :class_name => "PurchaseOrder", :foreign_key => :parent_id
	belongs_to :parent, :class_name => "PurchaseOrder"
	#has_paper_trail
	accepts_nested_attributes_for :purchase_order_items, allow_destroy: true

	def total_value
		purchase_order_items.sum('quantity * price')
	end	

end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	belongs_to :work

	validates :name, :agent, :rif, :address, presence: true
	validates :work, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :assignments, dependent: :destroy
  has_many :roles, :through => :assignments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	acts_as_messageable

	#Returning any kind of identification you want for the model
	def name
	  return self.email
	end

	#Returning the email address of the model if an email should be sent for this object (Message or Notification).
	#If no mail has to be sent, return nil.
	def mailboxer_email(object)
	  #Check if an email should be sent for that object
	  #if true
	  return "define_email@on_your.model"
	  #if false
	  #return nil
	end

end

app/models/valuation.rb
class Valuation < ActiveRecord::Base
	belongs_to :purchase_order
	has_many :valuation_items, :dependent => :destroy, :autosave => true
	accepts_nested_attributes_for :purchase_order
	accepts_nested_attributes_for :valuation_items, allow_destroy: true
end

app/models/valuation_item.rb
class ValuationItem < ActiveRecord::Base
	attr_accessor :total
	belongs_to :valuation
	belongs_to :purchase_order_item
end

app/models/work.rb
class Work < ActiveRecord::Base
	has_many :suppliers
	belongs_to :customer

	validates :customer, presence: true
	validates :name, :address, presence: true	
end

app/models/work_assignment.rb
class WorkAssignment < ActiveRecord::Base
  belongs_to :agent
  belongs_to :work
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:iva, :islr, :rl, :rfc)
    end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/valuations_helper.rb
module ValuationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t('fields.iva') %><br>
    <%= f.text_field :iva, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t('fields.islr') %><br>
    <%= f.text_field :islr, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t('fields.rl') %><br>
    <%= f.text_field :rl, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label t('fields.rfc') %><br>
    <%= f.text_field :rfc, class: 'form-control' %>
  </div>     
  <div class="form-group">
    <%= f.submit t('actions.save'), :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1 class="page-header"><%= t('actions.settings') %></h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Settings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>